Repository cms-nanoAOD/cmssw, pull requests merged in 2018-07, with the labels that each got.

#181 NanoAOD PRs 177, 179, 180 rebased to current 94X master
  PhysicsTools/NanoAOD/python/electrons_cff.py
  PhysicsTools/NanoAOD/python/jets_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/nano_cff.py
  PhysicsTools/NanoAOD/python/photons_cff.py
  PhysicsTools/NanoAOD/python/taus_cff.py
  PhysicsTools/NanoAOD/python/triggerObjects_cff.py
Labels: dqm config update (bot), test ok (bot), test started (bot)

#183 fix deepflavour discriminator
  PhysicsTools/NanoAOD/python/jets_cff.py
Labels: scram unit test failed (bot), test ok (bot), to be rebased to cmsswmaster

#185 Set up additions for 2016 legacy re-miniAOD
  Configuration/Eras/python/Modifier_run2_nanoAOD_94X2016_cff.py
  Configuration/StandardSequences/python/Eras.py
  PhysicsTools/NanoAOD/python/electrons_cff.py
  PhysicsTools/NanoAOD/python/photons_cff.py
Labels: test ok (bot)
