Repository cms-nanoAOD/cmssw, pull requests merged in 2018-08, with the labels that each got.

#186 Update tau MVA classifier decisions and raw values to be stored for 2016 94X NanoAOD
  PhysicsTools/NanoAOD/python/taus_cff.py
  PhysicsTools/NanoAOD/python/taus_updatedMVAIds_cff.py
Labels: test failed (bot), to be rebased to cmsswmaster

#188 Changing trigger backfill value
  PhysicsTools/NanoAOD/plugins/TriggerOutputBranches.cc
Labels: code checks ok (bot), to be rebased to cmsswmaster

#191 Latest deep flavour training for nanoAOD (for 2016 94X re-miniAOD)
  PhysicsTools/NanoAOD/python/nano_cff.py
Labels: test ok (bot), to be rebased to cmsswmaster
