Repository cms-nanoAOD/cmssw, pull requests merged in 2018-11, with the labels that each got.

#210 Adding JEC raw factor to AK8 subjets to reapply JEC in NANOAOD-tools
  PhysicsTools/NanoAOD/python/jets_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
Labels: test ok (bot)

#220 Explicit Summer16 label for 2016 cut based electron ID on 80X
  PhysicsTools/NanoAOD/python/electrons_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
Labels: scram unit test failed (bot), test ok (bot)

#221 Port PR 220 to master-94X
  PhysicsTools/NanoAOD/python/electrons_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
Labels: dqm config update (bot), test ok (bot)

#228 Store muon selectors payload in nanoAOD
  PhysicsTools/NanoAOD/python/muons_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
Labels: test ok (bot)

#226 Lepton ptRatio fix and additions
  PhysicsTools/NanoAOD/python/electrons_cff.py
  PhysicsTools/NanoAOD/python/muons_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
Labels: scram unit test failed (bot), test ok (bot), to be rebased to 94X, to be rebased to cmsswmaster

#214 Bug fix of era dependent configuration of MVAIso Tau-IDs
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/taus_cff.py
  PhysicsTools/NanoAOD/python/taus_updatedMVAIds_cff.py
Labels: scram unit test failed (bot), test ok (bot), to be rebased to 94X, to be rebased to cmsswmaster

#223 Sync electron content in 94X
  PhysicsTools/NanoAOD/python/electrons_cff.py
Labels: dqm config update (bot), test ok (bot)

#227 Store Higgs template cross section variables
  PhysicsTools/NanoAOD/plugins/SimpleFlatTableProducer.cc
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/particlelevel_cff.py
Labels: code checks ok (bot), scram unit test failed (bot), test ok (bot), to be rebased to 94X, to be rebased to cmsswmaster

#212 Add DeepAK8 tagger to NanoAOD
  PhysicsTools/NanoAOD/python/jets_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/nano_cff.py
Labels: test ok (bot), to be rebased to 102X, to be rebased to cmsswmaster

#232 Port PR 212 to master-102X
  PhysicsTools/NanoAOD/python/jets_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/nano_cff.py
Labels: test ok (bot)

#233 Port PR 212 to master-cmsswmaster
  PhysicsTools/NanoAOD/python/jets_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/nano_cff.py
Labels: test ok (bot)

#231 Type-1 corrections for PF and PUPPI MET
  PhysicsTools/NanoAOD/python/electrons_cff.py
  PhysicsTools/NanoAOD/python/met_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/nano_cff.py
  PhysicsTools/NanoAOD/python/photons_cff.py
Labels: test ok (bot)

#234 Switch on DeepFlavour on all 2016 and 2017 samples
  PhysicsTools/NanoAOD/python/nano_cff.py
Labels: scram unit test failed (bot), test ok (bot)

#240 NanoAOD processing for FastSim samples
  Configuration/Applications/python/ConfigBuilder.py
  PhysicsTools/NanoAOD/python/nano_cff.py
Labels: test ok (bot)

#241 Add Spring15 VID bitmap to 2016 samples
  PhysicsTools/NanoAOD/python/electrons_cff.py
Labels: test ok (bot), to be rebased to 94X, to be rebased to cmsswmaster

#243 Backport recent developments to 9_4_X
  Configuration/Applications/python/ConfigBuilder.py
  PhysicsTools/NanoAOD/plugins/SimpleFlatTableProducer.cc
  PhysicsTools/NanoAOD/python/electrons_cff.py
  PhysicsTools/NanoAOD/python/met_cff.py
  PhysicsTools/NanoAOD/python/muons_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/nano_cff.py
  PhysicsTools/NanoAOD/python/particlelevel_cff.py
  PhysicsTools/NanoAOD/python/photons_cff.py
  PhysicsTools/NanoAOD/python/taus_cff.py
  PhysicsTools/NanoAOD/python/taus_updatedMVAIds_cff.py
Labels: code checks ok (bot), dqm config update (bot), test ok (bot)

#247 Config updates
  PhysicsTools/NanoAOD/python/electrons_cff.py
  PhysicsTools/NanoAOD/python/jets_cff.py
  PhysicsTools/NanoAOD/python/muons_cff.py
  PhysicsTools/NanoAOD/python/nano_cff.py
  PhysicsTools/NanoAOD/python/photons_cff.py
Labels: code checks ok (bot), test ok (bot)

#248 Customize DQM content for different era modifiers
  PhysicsTools/NanoAOD/python/nanoDQM_cff.py
Labels: code checks ok (bot), test ok (bot)

#250 Forward port to 10_4_X
  PhysicsTools/NanoAOD/python/electrons_cff.py
  PhysicsTools/NanoAOD/python/jets_cff.py
  PhysicsTools/NanoAOD/python/met_cff.py
  PhysicsTools/NanoAOD/python/muons_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cff.py
  PhysicsTools/NanoAOD/python/nano_cff.py
  PhysicsTools/NanoAOD/python/photons_cff.py
Labels: test ok (bot)

#252 Fixes to AK8 treatment for 80X samples
  PhysicsTools/NanoAOD/python/jets_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cff.py
  PhysicsTools/NanoAOD/python/nano_cff.py
Labels: code checks ok (bot), test ok (bot)

#259 fixing 94X scale & smearing and updates
  PhysicsTools/NanoAOD/python/electrons_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
Labels: code checks ok (bot), test ok (bot), to be rebased to 94X, to be rebased to cmsswmaster

#258 Isotrack dev from 102 x
  PhysicsTools/NanoAOD/plugins/IsFromLostTrackMapProducer.cc
  PhysicsTools/NanoAOD/python/isotracks_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
Labels: code checks ok (bot), test ok (bot), to be rebased to 94X, to be rebased to cmsswmaster
