Repository cms-nanoAOD/cmssw, pull requests merged in 2018-05, with the labels that each got.

#120 Added b-tag SF EDProducer to get event weights
  PhysicsTools/NanoAOD/data/btagSF/CSVv2_94XSF_V2_B_F.csv
  PhysicsTools/NanoAOD/data/btagSF/CSVv2_Moriond17_B_H.csv
  PhysicsTools/NanoAOD/data/btagSF/DeepCSV_94XSF_V2_B_F.csv
  PhysicsTools/NanoAOD/data/btagSF/DeepCSV_Moriond17_B_H.csv
  PhysicsTools/NanoAOD/data/btagSF/cMVAv2_Moriond17_B_H.csv
  PhysicsTools/NanoAOD/plugins/BTagSFProducer.cc
  PhysicsTools/NanoAOD/plugins/BuildFile.xml
  PhysicsTools/NanoAOD/python/nano_cff.py
Labels: NeedFwdPort, code checks ok (bot), test ok (bot)

#162 Updating `triggerObjects_cff.py` to include physics based HLT trigger filter bit scheme
  PhysicsTools/NanoAOD/python/triggerObjects_cff.py
Labels: NeedFwdPort, test ok (bot)

#165 Fixing GenWeightsTable producer for MG26X samples
  PhysicsTools/NanoAOD/plugins/GenWeightsTableProducer.cc
Labels: code checks ok (bot), test ok (bot)

#168 Soft Activity bug fix, wrong input tag used
  PhysicsTools/NanoAOD/python/jets_cff.py
Labels: test ok (bot)

#171 Add PS weights to GenWeightsTableProducer
  PhysicsTools/NanoAOD/plugins/GenWeightsTableProducer.cc
Labels: code checks ok (bot), test ok (bot)
