Repository cms-nanoAOD/cmssw, pull requests merged in 2018-03, with the labels that each got.

#111 fixed segmentation violation that occurred in subjet analyses in case…
  PhysicsTools/SelectorUtils/interface/PFJetIDSelectionFunctor.h
Labels: code checks ok (bot), test ok (bot)

#123 Add two photon sc eta bits to nanoaod
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/photons_cff.py
Labels: dqm config update (bot), test ok (bot)

#135 Sort GenVisTau collection by their pT in GenVisTauProducer
  PhysicsTools/HepMCCandAlgos/plugins/GenVisTauProducer.cc
Labels: HOLD, bugfix, code checks ok (bot), test ok (bot)

#133 Fall17 EGM ID, effective areas and lepton MVA
  PhysicsTools/NanoAOD/data/effAreaMuons_cone03_pfNeuHadronsAndPhotons_94X.txt
  PhysicsTools/NanoAOD/data/el_BDTG_94X.weights.xml
  PhysicsTools/NanoAOD/data/mu_BDTG_94X.weights.xml
  PhysicsTools/NanoAOD/plugins/IsoValueMapProducer.cc
  PhysicsTools/NanoAOD/python/electrons_cff.py
  PhysicsTools/NanoAOD/python/muons_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
Labels: code checks ok (bot), test ok (bot)

#136 JetID 2017
  PhysicsTools/NanoAOD/python/jets_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/nano_cff.py
  PhysicsTools/SelectorUtils/interface/PFJetIDSelectionFunctor.h
  PhysicsTools/SelectorUtils/python/pfJetIDSelector_cfi.py
Labels: code checks ok (bot), ready, test ok (bot)

#143 E/gamma scale and smearing (94X v2)
  PhysicsTools/NanoAOD/python/electrons_cff.py
  PhysicsTools/NanoAOD/python/nano_cff.py
  PhysicsTools/NanoAOD/python/photons_cff.py
  PhysicsTools/NanoAOD/test/nano_cfg.py
Labels: test ok (bot)

#137 Fall17 photon ID
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/photons_cff.py
Labels: bugfix, test ok (bot)

#140 add the LHE particle four momenta
  PhysicsTools/NanoAOD/plugins/LHETablesProducer.cc
  PhysicsTools/NanoAOD/python/nano_cff.py
Labels: code checks ok (bot), test ok (bot)

#149 Fix LHE table crash on files that do not have LHE
  PhysicsTools/NanoAOD/plugins/LHETablesProducer.cc
  PhysicsTools/NanoAOD/test/runtests.sh
Labels: bugfix
