Repository cms-nanoAOD/cmssw, pull requests merged in 2018-04, with the labels that each got.

#150 Use correct JEC to compute lepton-to-jet variables
  PhysicsTools/NanoAOD/python/electrons_cff.py
  PhysicsTools/NanoAOD/python/muons_cff.py
  PhysicsTools/NanoAOD/python/nano_cff.py
Labels: test ok (bot)

#146 New MVA-based Tau-Ids (update)
  PhysicsTools/NanoAOD/python/nanoDQM_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/taus_cff.py
  PhysicsTools/NanoAOD/python/taus_updatedMVAIds_cff.py
  RecoTauTag/Configuration/python/loadRecoTauTagMVAsFromPrepDB_cfi.py
Labels: test started (bot)

#152 fixed lep-aware JEC formula
  PhysicsTools/NanoAOD/plugins/LeptonJetVarProducer.cc
Labels: code checks ok (bot), test ok (bot)

#156 Add deep flavour of MiniAOD v2 to nanoaod
  PhysicsTools/NanoAOD/python/jets_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
Labels: test ok (bot)

#160 80X MET Filters - bad muon flags
  PhysicsTools/NanoAOD/python/extraflags_cff.py
  PhysicsTools/NanoAOD/python/nano_cff.py
  RecoMET/METFilters/plugins/BadGlobalMuonTagger.cc
Labels: code checks ok (bot), test ok (bot)
