Repository cms-nanoAOD/cmssw, pull requests merged in 2019-05, with the labels that each got.

#334 Port PR 271 to master
  PhysicsTools/NanoAOD/python/jets_cff.py
  PhysicsTools/NanoAOD/python/nano_cff.py
Labels: test ok (bot)

#333 Add back MET covariance and significance
  PhysicsTools/NanoAOD/python/met_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
Labels: test ok (bot)

#335 Low pt jets for for T1 MET re-correction
  JetMETCorrections/Type1MET/interface/JetCleanerForType1METT.h
  PhysicsTools/NanoAOD/python/jets_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/nano_cff.py
Labels: code checks ok (bot), test ok (bot)

#340 Adding DeepFlavour C discriminator
  PhysicsTools/NanoAOD/python/jets_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/nano_cff.py
Labels: test ok (bot)

#336 Update of lepton MVA
  PhysicsTools/NanoAOD/python/electrons_cff.py
  PhysicsTools/NanoAOD/python/muons_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
Labels: code checks ok (bot), test ok (bot)

#341 DeepBoostedJetV2 + HTXS + gainSeed
  PhysicsTools/NanoAOD/plugins/EGMSeedGainProducer.cc
  PhysicsTools/NanoAOD/python/electrons_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/nano_cff.py
  PhysicsTools/NanoAOD/python/particlelevel_cff.py
  PhysicsTools/NanoAOD/python/photons_cff.py
Labels: code checks ok (bot), test ok (bot), to be rebased to cmsswmaster

#343 Port PR 335 336 341
  JetMETCorrections/Type1MET/interface/JetCleanerForType1METT.h
  PhysicsTools/NanoAOD/plugins/EGMSeedGainProducer.cc
  PhysicsTools/NanoAOD/python/electrons_cff.py
  PhysicsTools/NanoAOD/python/jets_cff.py
  PhysicsTools/NanoAOD/python/muons_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/nano_cff.py
  PhysicsTools/NanoAOD/python/particlelevel_cff.py
  PhysicsTools/NanoAOD/python/photons_cff.py
Labels: code checks ok (bot), test ok (bot)

#342 Backport PR 340
  PhysicsTools/NanoAOD/python/jets_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/nano_cff.py
Labels: code checks ok (bot), test ok (bot)

#353 [Backport] Adding DeepDoubleX to nano
  PhysicsTools/NanoAOD/python/jets_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/nano_cff.py
Labels: code checks ok (bot), test ok (bot)

#359 Store flag to recover Ele32 path in 2017 data
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/triggerObjects_cff.py
Labels: code checks ok (bot), test ok (bot)

#357 add e/gamma scale & smearing for 2018 data/MC
  PhysicsTools/NanoAOD/python/electrons_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/photons_cff.py
Labels: code checks ok (bot), test ok (bot)

#362 Fix L1 decision storage in 102X
  PhysicsTools/NanoAOD/plugins/L1TriggerResultsConverter.cc
Labels: code checks ok (bot), test ok (bot)

#360 Pog muon loose
  PhysicsTools/NanoAOD/python/isotracks_cff.py
  PhysicsTools/NanoAOD/python/muons_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/nano_cff.py
Labels: code checks ok (bot), test ok (bot)

#246 Adding a few jet and event variables to prepare for automatic JEC workflows
  PhysicsTools/NanoAOD/plugins/NPUTablesProducer.cc
  PhysicsTools/NanoAOD/python/globals_cff.py
  PhysicsTools/NanoAOD/python/jets_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
Labels: code checks ok (bot), test ok (bot), to be rebased to cmsswmaster

#364 Added HighPt info, puppiIsoId, softMvaScore
  PhysicsTools/NanoAOD/python/muons_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
Labels: test ok (bot), to be rebased to 102X

#365 Port recent pull requests to master
  PhysicsTools/NanoAOD/plugins/NPUTablesProducer.cc
  PhysicsTools/NanoAOD/python/electrons_cff.py
  PhysicsTools/NanoAOD/python/globals_cff.py
  PhysicsTools/NanoAOD/python/isotracks_cff.py
  PhysicsTools/NanoAOD/python/jets_cff.py
  PhysicsTools/NanoAOD/python/muons_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/nano_cff.py
  PhysicsTools/NanoAOD/python/photons_cff.py
  PhysicsTools/NanoAOD/python/triggerObjects_cff.py
Labels: code checks ok (bot), test ok (bot)

#355 Per-object variable precision + tau ancestor dressed lepton bit
  PhysicsTools/NanoAOD/interface/SimpleFlatTableProducer.h
  PhysicsTools/NanoAOD/plugins/GenJetTauTaggerProducer.cc
  PhysicsTools/NanoAOD/python/common_cff.py
  PhysicsTools/NanoAOD/python/genparticles_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/particlelevel_cff.py
Labels: code checks ok (bot), test ok (bot)

#367 Port PR 355 + HTXS stage 1.1 + top mass
  PhysicsTools/NanoAOD/interface/SimpleFlatTableProducer.h
  PhysicsTools/NanoAOD/plugins/GenJetTauTaggerProducer.cc
  PhysicsTools/NanoAOD/plugins/GenWeightsTableProducer.cc
  PhysicsTools/NanoAOD/python/common_cff.py
  PhysicsTools/NanoAOD/python/genparticles_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/particlelevel_cff.py
Labels: code checks ok (bot), test ok (bot)

#369 Port PR 364 367 to 102X
  PhysicsTools/NanoAOD/plugins/GenWeightsTableProducer.cc
  PhysicsTools/NanoAOD/python/genparticles_cff.py
  PhysicsTools/NanoAOD/python/muons_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/particlelevel_cff.py
Labels: code checks ok (bot), test ok (bot)
