Repository cms-nanoAOD/cmssw, pull requests merged in 2019-10, with the labels that each got.

#405 Port recent pull requests to 106X
  PhysicsTools/NanoAOD/plugins/EventStringOutputBranches.cc
  PhysicsTools/NanoAOD/plugins/EventStringOutputBranches.h
  PhysicsTools/NanoAOD/plugins/GenWeightsTableProducer.cc
  PhysicsTools/NanoAOD/plugins/NanoAODOutputModule.cc
  PhysicsTools/NanoAOD/plugins/VertexTableProducer.cc
  PhysicsTools/NanoAOD/python/NanoAODEDMEventContent_cff.py
  PhysicsTools/NanoAOD/python/jets_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/nano_cff.py
  PhysicsTools/NanoAOD/python/triggerObjects_cff.py
Labels: code checks ok (bot), dqm config update (bot), test ok (bot)

#406 Port recent pull requests to master
  Configuration/Eras/python/Modifier_run2_nanoAOD_106Xv1_cff.py
  Configuration/StandardSequences/python/Eras.py
  PhysicsTools/NanoAOD/plugins/EventStringOutputBranches.cc
  PhysicsTools/NanoAOD/plugins/EventStringOutputBranches.h
  PhysicsTools/NanoAOD/plugins/GenWeightsTableProducer.cc
  PhysicsTools/NanoAOD/plugins/NanoAODOutputModule.cc
  PhysicsTools/NanoAOD/plugins/VertexTableProducer.cc
  PhysicsTools/NanoAOD/python/NanoAODEDMEventContent_cff.py
  PhysicsTools/NanoAOD/python/jets_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/nano_cff.py
  PhysicsTools/NanoAOD/python/taus_cff.py
Labels: code checks ok (bot), dqm config update (bot), test ok (bot)

#408 Activate deepTau in 106X
  Configuration/Eras/python/Modifier_run2_nanoAOD_106Xv1_cff.py
  Configuration/StandardSequences/python/Eras.py
  PhysicsTools/NanoAOD/python/nano_cff.py
  PhysicsTools/NanoAOD/python/taus_cff.py
Labels: dqm config update (bot), test ok (bot)

#407 Activate DeepTauV2p1 in all releases
  PhysicsTools/NanoAOD/python/nano_cff.py
  PhysicsTools/NanoAOD/python/taus_cff.py
Labels: dqm config update (bot), test ok (bot)

#412 More variables and looser preselection on SV
  PhysicsTools/NanoAOD/plugins/VertexTableProducer.cc
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
Labels: code checks ok (bot), dqm config update (bot), test ok (bot), to be rebased to 102X, to be rebased to 106X

#414 Add HEEP ID VID bitmap
  PhysicsTools/NanoAOD/python/electrons_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
Labels: dqm config update (bot), test ok (bot), to be rebased to 102X, to be rebased to 106X

#415 Save mass of BSM genparticles
  PhysicsTools/NanoAOD/python/genparticles_cff.py
Labels: to be rebased to 102X, to be rebased to 106X

#420 Port recent pull requests to 106X
  PhysicsTools/NanoAOD/plugins/VertexTableProducer.cc
  PhysicsTools/NanoAOD/python/electrons_cff.py
  PhysicsTools/NanoAOD/python/genparticles_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
Labels: code checks ok (bot), dqm config update (bot), test ok (bot)

#419 Port recent pull requests to 102X
  PhysicsTools/NanoAOD/plugins/VertexTableProducer.cc
  PhysicsTools/NanoAOD/python/electrons_cff.py
  PhysicsTools/NanoAOD/python/genparticles_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
Labels: code checks ok (bot), dqm config update (bot), test ok (bot)

#424 Update jet ID to latest recommendations
  PhysicsTools/NanoAOD/python/jets_cff.py
Labels: code checks ok (bot), dqm config update (bot), test ok (bot), to be rebased to 102X, to be rebased to 106X

#417 Test PR NanoAODv6 master [part2]
  PhysicsTools/NanoAOD/plugins/VertexTableProducer.cc
  PhysicsTools/NanoAOD/python/muons_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
Labels: code checks ok (bot), test ok (bot)

#416 Adding FSR recovery (only NanoAOD config)
  PhysicsTools/NanoAOD/python/muons_cff.py
Labels: HOLD, code checks ok (bot), dqm config update (bot), needs new CMSSW release, test ok (bot)

#426 Test PR NanoAODv6 102X
  PhysicsTools/NanoAOD/python/jets_cff.py
  PhysicsTools/NanoAOD/python/muons_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
Labels: code checks ok (bot), test ok (bot)

#425 Test PR NanoAODv6 106X
  PhysicsTools/NanoAOD/python/jets_cff.py
  PhysicsTools/NanoAOD/python/muons_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
Labels: code checks ok (bot), test ok (bot)

#435 Fix usage of eras for UL samples
  Configuration/Eras/python/Era_Run2_2016_cff.py
  Configuration/Eras/python/Era_Run2_2017_cff.py
  Configuration/Eras/python/Era_Run2_2018_cff.py
  Configuration/Eras/python/Modifier_run2_jme_2016_cff.py
  Configuration/Eras/python/Modifier_run2_jme_2017_cff.py
  PhysicsTools/NanoAOD/python/electrons_cff.py
  PhysicsTools/NanoAOD/python/jets_cff.py
  PhysicsTools/NanoAOD/python/met_cff.py
  PhysicsTools/NanoAOD/python/muons_cff.py
  PhysicsTools/NanoAOD/python/taus_cff.py
  PhysicsTools/NanoAOD/python/taus_updatedMVAIds_cff.py
  PhysicsTools/NanoAOD/python/triggerObjects_cff.py
Labels: bugfix, test ok (bot)

#440 Fix usage of eras for UL samples [106X]
  Configuration/Eras/python/Era_Run2_2016_cff.py
  Configuration/Eras/python/Era_Run2_2017_cff.py
  Configuration/Eras/python/Era_Run2_2018_cff.py
  Configuration/Eras/python/Modifier_run2_jme_2016_cff.py
  Configuration/Eras/python/Modifier_run2_jme_2017_cff.py
  PhysicsTools/NanoAOD/python/electrons_cff.py
  PhysicsTools/NanoAOD/python/jets_cff.py
  PhysicsTools/NanoAOD/python/met_cff.py
  PhysicsTools/NanoAOD/python/muons_cff.py
  PhysicsTools/NanoAOD/python/triggerObjects_cff.py
Labels: code checks ok (bot), test ok (bot)

#445 Fix wrong parenthesis in era switches
  PhysicsTools/NanoAOD/python/nano_cff.py
Labels: bugfix, code checks ok (bot), test ok (bot)
