Repository cms-nanoAOD/cmssw, pull requests merged in 2019-04, with the labels that each got.

#305 Solve bugs in lepton matching for Tau_genPartFlav [102X]
  PhysicsTools/NanoAOD/plugins/CandMCMatchTableProducer.cc
  PhysicsTools/NanoAOD/python/taus_cff.py
Labels: code checks ok (bot), test ok (bot), to be rebased to cmsswmaster

#300 add deepTag_H, deepTag_QCD, deepTag_QCDothers
  PhysicsTools/NanoAOD/python/jets_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
Labels: test ok (bot), to be rebased to cmsswmaster

#294 Split SimpleFlatTableProducer plugin into header and implementation
  PhysicsTools/NanoAOD/interface/SimpleFlatTableProducer.h
  PhysicsTools/NanoAOD/plugins/SimpleFlatTableProducerPlugins.cc
Labels: code checks ok (bot), test ok (bot), to be rebased to cmsswmaster

#276 New MVA-based anti-e Tau-Id
  PhysicsTools/NanoAOD/python/nanoDQM_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/taus_cff.py
  PhysicsTools/NanoAOD/python/taus_updatedMVAIds_cff.py
Labels: test ok (bot), to be rebased to cmsswmaster

#316 Port PR 294 300 305 to master
  PhysicsTools/NanoAOD/interface/SimpleFlatTableProducer.h
  PhysicsTools/NanoAOD/plugins/CandMCMatchTableProducer.cc
  PhysicsTools/NanoAOD/plugins/SimpleFlatTableProducerPlugins.cc
  PhysicsTools/NanoAOD/python/jets_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/taus_cff.py
Labels: code checks ok (bot), test ok (bot)

#317 Port PR 276 to master
  PhysicsTools/NanoAOD/python/nanoDQM_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/taus_cff.py
  PhysicsTools/NanoAOD/python/taus_updatedMVAIds_cff.py
Labels: test ok (bot)

#318 Feature pack Apr16
  PhysicsTools/NanoAOD/plugins/GlobalVariablesTableProducer.cc
  PhysicsTools/NanoAOD/python/electrons_cff.py
  PhysicsTools/NanoAOD/python/jets_cff.py
  PhysicsTools/NanoAOD/python/muons_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/nano_cff.py
  PhysicsTools/NanoAOD/python/particlelevel_cff.py
  PhysicsTools/NanoAOD/python/photons_cff.py
  PhysicsTools/NanoAOD/python/taus_cff.py
  PhysicsTools/NanoAOD/python/taus_updatedMVAIds_cff.py
  PhysicsTools/NanoAOD/python/triggerObjects_cff.py
  PhysicsTools/NanoAOD/python/ttbarCategorization_cff.py
Labels: code checks ok (bot), test ok (bot), to be rebased to cmsswmaster

#319 Port PR 318 to master
  PhysicsTools/NanoAOD/plugins/GlobalVariablesTableProducer.cc
  PhysicsTools/NanoAOD/python/electrons_cff.py
  PhysicsTools/NanoAOD/python/jets_cff.py
  PhysicsTools/NanoAOD/python/muons_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/nano_cff.py
  PhysicsTools/NanoAOD/python/particlelevel_cff.py
  PhysicsTools/NanoAOD/python/photons_cff.py
  PhysicsTools/NanoAOD/python/taus_cff.py
  PhysicsTools/NanoAOD/python/taus_updatedMVAIds_cff.py
  PhysicsTools/NanoAOD/python/triggerObjects_cff.py
  PhysicsTools/NanoAOD/python/ttbarCategorization_cff.py
Labels: code checks ok (bot), test ok (bot)

#329 Fix HLT label for UL data reprocessing
  PhysicsTools/NanoAOD/python/nano_cff.py
Labels: bugfix, test ok (bot)

#328 L1 unprefireable bit + MET covariance/significance
  PhysicsTools/NanoAOD/plugins/L1TriggerResultsConverter.cc
  PhysicsTools/NanoAOD/python/met_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/nano_cff.py
Labels: code checks ok (bot), test ok (bot)

#271 QGL and jet ID updates
  PhysicsTools/NanoAOD/python/jets_cff.py
  PhysicsTools/NanoAOD/python/nano_cff.py
Labels: test ok (bot)
