Repository cms-nanoAOD/cmssw, pull requests merged in 2019-11, with the labels that each got.

#418 Improve photon genpartflav
  PhysicsTools/NanoAOD/plugins/CandMCMatchTableProducer.cc
Labels: code checks ok (bot), test ok (bot)

#433 Update b-jet energy regression
  PhysicsTools/NanoAOD/python/jets_cff.py
Labels: test ok (bot)

#430 Adding c-jet energy regression evaluation
  PhysicsTools/NanoAOD/python/jets_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
Labels: test ok (bot)

#453 Consolidate electron TrigObj quality bits, add filter for CaloIdVTGsfTrkIdT
  PhysicsTools/NanoAOD/python/triggerObjects_cff.py
Labels: test ok (bot), to be rebased to 102X, to be rebased to 106X

#448 Updated Muon Selectors
  PhysicsTools/NanoAOD/python/muons_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
Labels: test ok (bot), to be rebased to 106X

#456 nB and nC hadrons in fat- and sub-jets + AK8 gen matching
  PhysicsTools/NanoAOD/python/jets_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
Labels: test ok (bot)
