Repository cms-nanoAOD/cmssw, pull requests merged in 2019-09, with the labels that each got.

#398 Save model string in randomized parameter scans + fix vtx formula
  PhysicsTools/NanoAOD/plugins/EventStringOutputBranches.cc
  PhysicsTools/NanoAOD/plugins/EventStringOutputBranches.h
  PhysicsTools/NanoAOD/plugins/GenWeightsTableProducer.cc
  PhysicsTools/NanoAOD/plugins/NanoAODOutputModule.cc
  PhysicsTools/NanoAOD/plugins/VertexTableProducer.cc
  PhysicsTools/NanoAOD/python/NanoAODEDMEventContent_cff.py
  PhysicsTools/NanoAOD/python/nano_cff.py
Labels: code checks ok (bot), test ok (bot), to be rebased to 106X, to be rebased to cmsswmaster

#396 Update DeepTauID to ver. 2017v2p1
  HLTrigger/Configuration/python/Tools/confdbOfflineConverter.py
  PhysicsTools/NanoAOD/python/nano_cff.py
  PhysicsTools/NanoAOD/python/taus_cff.py
  RecoTauTag/RecoTau/plugins/DeepTauId.cc
  RecoTauTag/RecoTau/python/tools/runTauIdMVA.py
  RecoTauTag/RecoTau/test/runDeepTauIDsOnMiniAOD.py
Labels: code checks ok (bot), test ok (bot), to be rebased to 106X, to be rebased to cmsswmaster

#371 Add non-decorrelated DeepDoubleX tagger scores
  PhysicsTools/NanoAOD/python/jets_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/nano_cff.py
Labels: test ok (bot), to be rebased to 106X, to be rebased to cmsswmaster

#395 Remove trigger object redundancy of OverlapFilterIsoEle bits
  PhysicsTools/NanoAOD/python/triggerObjects_cff.py
Labels: dqm config update (bot), test ok (bot), to be rebased to 106X, to be rebased to cmsswmaster
