Repository cms-nanoAOD/cmssw, pull requests merged in 2020-01, with the labels that each got.

#469 c-jet energy regression for 2016 and 2018
  PhysicsTools/NanoAOD/python/jets_cff.py
Labels: test ok (bot)

#467 Add rawpuppimet
  PhysicsTools/NanoAOD/python/met_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
Labels: test ok (bot), to be rebased to 102X, to be rebased to 106X

#473 Correctly fill trigger bits for disappeared paths
  PhysicsTools/NanoAOD/plugins/TriggerOutputBranches.cc
  PhysicsTools/NanoAOD/plugins/TriggerOutputBranches.h
Labels: bugfix, code checks ok (bot), code format ok (bot), test ok (bot), to be rebased to 102X, to be rebased to 106X

#459 Adding HTXS stage 1.2 to nanoAOD
  PhysicsTools/NanoAOD/python/particlelevel_cff.py
Labels: code checks ok (bot), code format ok (bot), test ok (bot)

#476 Update to 10_2_20_UL + backports
  CondFormats/JetMETObjects/interface/JetResolutionObject.h
  CondFormats/JetMETObjects/src/JetResolutionObject.cc
  Configuration/Eras/python/Era_Run2_2016_cff.py
  Configuration/Eras/python/Era_Run2_2017_cff.py
  Configuration/Eras/python/Era_Run2_2018_cff.py
  Configuration/Eras/python/Modifier_run2_jme_2016_cff.py
  Configuration/Eras/python/Modifier_run2_jme_2017_cff.py
  Configuration/Generator/python/MCTunes2017/PythiaCP5CR1TuneSettings_cfi.py
  Configuration/Generator/python/MCTunes2017/PythiaCP5CR2TuneSettings_cfi.py
  FWCore/Framework/python/test/cmsExceptionsFatalOption_cff.py
  FWCore/MessageLogger/scripts/edmFjrDump
  FWCore/Utilities/interface/EDMException.h
  FWCore/Utilities/interface/stemFromPath.h
  FWCore/Utilities/src/EDMException.cc
  FWCore/Utilities/src/stemFromPath.cc
  FWCore/Utilities/test/BuildFile.xml
  FWCore/Utilities/test/test_catch2_main.cc
  FWCore/Utilities/test/test_catch2_stemFromPath.cc
  FastSimulation/SimplifiedGeometryPropagator/plugins/FastTrackDeDxProducer.cc
  GeneratorInterface/GenFilters/src/LHEPtFilter.cc
  GeneratorInterface/RivetInterface/interface/RivetAnalysis.h
  GeneratorInterface/RivetInterface/python/particleLevel_cfi.py
  GeneratorInterface/RivetInterface/src/HiggsTemplateCrossSections.cc
  IOPool/Input/src/RootEmbeddedFileSequence.cc
  IOPool/Input/src/RootEmbeddedFileSequence.h
  IOPool/Input/src/RootFile.cc
  IOPool/Input/src/RootFile.h
  IOPool/Input/src/RootPrimaryFileSequence.cc
  IOPool/Input/src/RootPrimaryFileSequence.h
  IOPool/Input/src/RootSecondaryFileSequence.cc
  IOPool/Input/src/RootSecondaryFileSequence.h
  IOPool/Input/test/PoolGUIDTest_cfg.py
  IOPool/Input/test/PrePoolInputTest_cfg.py
  IOPool/Input/test/TestPoolInput.sh
  JetMETCorrections/Modules/interface/JetResolution.h
  JetMETCorrections/Modules/src/JetResolution.cc
  PhysicsTools/NanoAOD/plugins/CandMCMatchTableProducer.cc
  PhysicsTools/NanoAOD/plugins/TriggerOutputBranches.cc
  PhysicsTools/NanoAOD/plugins/TriggerOutputBranches.h
  PhysicsTools/NanoAOD/python/jets_cff.py
  PhysicsTools/NanoAOD/python/met_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/particlelevel_cff.py
  PhysicsTools/NanoAOD/python/triggerObjects_cff.py
  PhysicsTools/PatUtils/interface/SmearedJetProducerT.h
  PhysicsTools/PatUtils/test/runJERsmearingOnMiniAOD.py
  RecoTracker/Configuration/python/RecoTracker_cff.py
  RecoTracker/DeDx/python/dedxEstimators_cff.py
  SimDataFormats/HTXS/interface/HiggsTemplateCrossSections.h
Labels: code checks ok (bot), dqm config update (bot), test ok (bot)

#449 Add isolated gen-level photons to the nanoaod
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/particlelevel_cff.py
Labels: code checks ok (bot), code format ok (bot), test ok (bot), to be rebased to 102X, to be rebased to 106X

#478 Minor fixes
  PhysicsTools/NanoAOD/plugins/GenWeightsTableProducer.cc
  PhysicsTools/NanoAOD/plugins/NanoAODOutputModule.cc
  PhysicsTools/NanoAOD/plugins/TriggerOutputBranches.cc
  PhysicsTools/NanoAOD/plugins/TriggerOutputBranches.h
  PhysicsTools/NanoAOD/python/jets_cff.py
  PhysicsTools/NanoAOD/python/triggerObjects_cff.py
  PhysicsTools/NanoAOD/test/inspectNanoFile.py
Labels: code checks ok (bot), code format ok (bot), test ok (bot)

#479 Fix muon IP sign [rebased]
  PhysicsTools/NanoAOD/python/muons_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/PatAlgos/plugins/LeptonUpdater.cc
Labels: code checks ok (bot), code format ok (bot), test ok (bot), to be rebased to 102X, to be rebased to 106X

#464 Update photon IDs in 2016 nano
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/photons_cff.py
Labels: code checks ok (bot), code format ok (bot), test ok (bot)

#485 keeping unclustered sumPt in nanoAOD
  PhysicsTools/NanoAOD/python/met_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
Labels: code checks ok (bot), code format ok (bot), dqm config update (bot), test ok (bot)

#481 Add puppimet uncertainties
  PhysicsTools/NanoAOD/python/met_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
Labels: code checks ok (bot), code format ok (bot), test ok (bot), to be rebased to 102X, to be rebased to 106X

#491 Introduce normalized data members in MergeableCounterTable
  DataFormats/NanoAOD/interface/MergeableCounterTable.h
  DataFormats/NanoAOD/src/classes_def.xml
  PhysicsTools/NanoAOD/plugins/GenWeightsTableProducer.cc
  PhysicsTools/NanoAOD/plugins/SummaryTableOutputBranches.cc
  PhysicsTools/NanoAOD/plugins/SummaryTableOutputBranches.h
Labels: code checks ok (bot), code format ok (bot), test ok (bot), to be rebased to 102X, to be rebased to 106X

#458 Add Supercluster energy storage for electrons
  PhysicsTools/NanoAOD/python/electrons_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
Labels: code checks ok (bot), code format ok (bot), test ok (bot), to be rebased to 102X, to be rebased to 106X

#484 Adding lepton in fatjet vars
  PhysicsTools/NanoAOD/BuildFile.xml
  PhysicsTools/NanoAOD/plugins/BuildFile.xml
  PhysicsTools/NanoAOD/plugins/LeptonInJetProducer.cc
  PhysicsTools/NanoAOD/python/jets_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/nano_cff.py
Labels: code checks ok (bot), code format ok (bot), test ok (bot), to be rebased to 102X, to be rebased to 106X

#480 Saving LHE weights in nanoAOD when using randomised parameter scans [rebased]
  PhysicsTools/NanoAOD/plugins/GenWeightsTableProducer.cc
  PhysicsTools/NanoAOD/python/nano_cff.py
Labels: code checks ok (bot), code format ok (bot), test ok (bot), to be rebased to 102X, to be rebased to 106X
