Repository cms-nanoAOD/cmssw, pull requests merged in 2020-03, with the labels that each got.

#506 Fix PSWeight being incorrectly scaled
  PhysicsTools/NanoAOD/plugins/GenWeightsTableProducer.cc
Labels: code checks ok (bot), code format ok (bot), test ok (bot), to be rebased to 102X, to be rebased to 106X

#493 Add pileup jet ID discriminant + add 94X and 102X training
  PhysicsTools/NanoAOD/python/jets_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
Labels: test ok (bot), to be rebased to 102X, to be rebased to 106X

#494 Triggers objects for triple b-tag paths and skip trgObj without required filters
  PhysicsTools/NanoAOD/plugins/TriggerObjectTableProducer.cc
  PhysicsTools/NanoAOD/python/triggerObjects_cff.py
Labels: code checks ok (bot), code format ok (bot), test ok (bot), to be rebased to 102X, to be rebased to 106X

#510 Backports for NanoAODv7 in 10_2_X
  DataFormats/NanoAOD/interface/MergeableCounterTable.h
  DataFormats/NanoAOD/src/classes_def.xml
  PhysicsTools/NanoAOD/BuildFile.xml
  PhysicsTools/NanoAOD/plugins/BuildFile.xml
  PhysicsTools/NanoAOD/plugins/GenWeightsTableProducer.cc
  PhysicsTools/NanoAOD/plugins/LHETablesProducer.cc
  PhysicsTools/NanoAOD/plugins/LeptonInJetProducer.cc
  PhysicsTools/NanoAOD/plugins/NanoAODOutputModule.cc
  PhysicsTools/NanoAOD/plugins/SummaryTableOutputBranches.cc
  PhysicsTools/NanoAOD/plugins/SummaryTableOutputBranches.h
  PhysicsTools/NanoAOD/plugins/TriggerObjectTableProducer.cc
  PhysicsTools/NanoAOD/plugins/TriggerOutputBranches.cc
  PhysicsTools/NanoAOD/plugins/TriggerOutputBranches.h
  PhysicsTools/NanoAOD/python/electrons_cff.py
  PhysicsTools/NanoAOD/python/genparticles_cff.py
  PhysicsTools/NanoAOD/python/jets_cff.py
  PhysicsTools/NanoAOD/python/met_cff.py
  PhysicsTools/NanoAOD/python/muons_cff.py
  PhysicsTools/NanoAOD/python/nanoDQM_cfi.py
  PhysicsTools/NanoAOD/python/nano_cff.py
  PhysicsTools/NanoAOD/python/particlelevel_cff.py
  PhysicsTools/NanoAOD/python/photons_cff.py
  PhysicsTools/NanoAOD/python/triggerObjects_cff.py
  PhysicsTools/NanoAOD/test/inspectNanoFile.py
  PhysicsTools/PatAlgos/plugins/LeptonUpdater.cc
  RecoJets/JetProducers/plugins/BetaStarVarProducer.cc
Labels: code checks ok (bot), test ok (bot)
